import { useState, useRef, useEffect, useCallback } from 'react'
import { Send, Bot, User, Loader2, Sparkles } from 'lucide-react'
import type { Report, TagReading } from '../lib/supabase'

type Message = {
  role: 'user' | 'assistant'
  content: string
  time: string
}

type Props = {
  report: Report | null
  readings: TagReading[]
  selectedTime: string
}

function formatVal(v: string | number): string {
  if (typeof v === 'number') return parseFloat(v.toFixed(2)).toString()
  const n = parseFloat(v)
  return isNaN(n) ? String(v) : parseFloat(n.toFixed(2)).toString()
}

function buildContext(report: Report | null, readings: TagReading[], selectedTime: string): string {
  if (!report || readings.length === 0) {
    return 'No report is currently loaded. The user has not uploaded any Excel file yet.'
  }

  const time = selectedTime || 'latest'
  const lines: string[] = []
  lines.push(`Report: ${report.sheet_name}`)
  lines.push(`Report Date: ${report.report_date || 'Not specified'}`)
  lines.push(`Total Tags: ${report.tag_count}`)
  lines.push(`Selected Time Column: ${time}`)
  lines.push('')
  lines.push('Tag Readings (tag | description | unit | value):')

  for (const r of readings) {
    let val: string | number = '—'
    if (selectedTime && r.values_by_time && r.values_by_time[selectedTime] !== undefined && r.values_by_time[selectedTime] !== null) {
      val = formatVal(r.values_by_time[selectedTime])
    } else if (r.value !== null) {
      val = formatVal(r.value)
    } else if (r.raw_value) {
      val = r.raw_value
    }
    lines.push(`  ${r.tag} | ${r.description} | ${r.unit || '-'} | ${val}`)
  }

  return lines.join('\n')
}

function generateReply(question: string, report: Report | null, readings: TagReading[], selectedTime: string): string {
  const q = question.toLowerCase().trim()
  const time = selectedTime || 'latest'

  if (!report || readings.length === 0) {
    return "No report is currently loaded. Please upload a Jalkheri Excel file first, and then I'll be able to answer questions about your plant data."
  }

  const getVal = (tag: string): string | null => {
    const r = readings.find((item) => item.tag.toLowerCase() === tag.toLowerCase())
    if (!r) return null
    if (selectedTime && r.values_by_time && r.values_by_time[selectedTime] !== undefined && r.values_by_time[selectedTime] !== null) {
      return formatVal(r.values_by_time[selectedTime])
    }
    if (r.value !== null) return formatVal(r.value)
    return r.raw_value || null
  }

  const searchReadings = (term: string): TagReading[] => {
    const t = term.toLowerCase()
    return readings.filter((r) =>
      r.tag.toLowerCase().includes(t) || r.description.toLowerCase().includes(t)
    )
  }

  // TG Load
  if (q.includes('tg load') || q.includes('turbine load') || q.includes('power') || q.includes('generation') || q.includes('mw')) {
    const v = getVal('MW001')
    if (v) return `The TG Load (Active Power) is ${v} MW for the ${time} reading. This is the current power generation output of the turbine generator.`
    return 'TG Load data is not available in the current report.'
  }

  // Boiler MS Flow
  if (q.includes('main steam flow') || q.includes('boiler ms flow') || q.includes('steam flow') || q.includes('ms flow')) {
    const v = getVal('LBA10FF001_TON')
    if (v) return `The Main Steam Flow is ${v} TNE/H (tonnes per hour) for the ${time} reading. This represents the rate of steam being generated by the boiler.`
    return 'Main Steam Flow data is not available in the current report.'
  }

  // Steam Pressure
  if (q.includes('steam pressure') || q.includes('ms pressure') || q.includes('live steam pr') || q.includes('boiler pressure')) {
    const v = getVal('LBA10CP001XQ01')
    if (v) return `The Main Steam Pressure is ${v} kg/cm² for the ${time} reading. This is the live steam pressure at the boiler outlet.`
    return 'Main Steam Pressure data is not available in the current report.'
  }

  // Steam Temperature
  if (q.includes('steam temp') || q.includes('ms temp') || q.includes('live steam temp') || q.includes('boiler temp')) {
    const v = getVal('LBA10CT001XQ01')
    if (v) return `The Main Steam Temperature is ${v} °C for the ${time} reading. This is the live steam temperature at the boiler outlet.`
    return 'Main Steam Temperature data is not available in the current report.'
  }

  // Feed water
  if (q.includes('feed water') || q.includes('feedwater') || q.includes('feed temp')) {
    const results = searchReadings('feedwater')
    if (results.length > 0) {
      const lines = results.map((r) => {
        const v = getVal(r.tag) || '—'
        return `  • ${r.tag}: ${r.description} = ${v} ${r.unit || ''}`
      })
      return `Here are the feed water related readings for ${time}:\n${lines.join('\n')}`
    }
    return 'Feed water data is not available in the current report.'
  }

  // Economizer
  if (q.includes('economizer') || q.includes('eco') || q.includes('effectiveness')) {
    const ecoOutlet = getVal('HAC30CT001XQ01')
    const ecoInlet = getVal('LAA10CT001XQ01')
    const flueInlet = getVal('HNA10CT001XQ01')
    const flueOutlet = getVal('HNA20CT001XQ01')

    const lines: string[] = []
    if (ecoOutlet) lines.push(`  • Feed Water Temp ECO Outlet: ${ecoOutlet} °C`)
    if (ecoInlet) lines.push(`  • Feed Water Temp ECO Inlet: ${ecoInlet} °C`)
    if (flueInlet) lines.push(`  • Flue Gas Inlet Temp: ${flueInlet} °C`)
    if (flueOutlet) lines.push(`  • Flue Gas Outlet Temp: ${flueOutlet} °C`)

    if (ecoOutlet && ecoInlet && flueInlet && flueOutlet) {
      const feedDelta = parseFloat(ecoOutlet) - parseFloat(ecoInlet)
      const flueDelta = parseFloat(flueInlet) - parseFloat(flueOutlet)
      const effectiveness = flueDelta !== 0 ? (feedDelta / flueDelta) * 100 : 0
      lines.push(`  • Feedwater Delta T: ${feedDelta.toFixed(2)} °C`)
      lines.push(`  • Flue Gas Delta T: ${flueDelta.toFixed(2)} °C`)
      lines.push(`  • Calculated Effectiveness: ${effectiveness.toFixed(2)} %`)
      const rating = effectiveness < 25 ? 'Very Poor (below 25%)' : effectiveness < 40 ? 'Below Average' : effectiveness < 55 ? 'Average' : 'Good'
      lines.push(`  • Rating: ${rating}`)
      return `Economizer analysis for ${time}:\n${lines.join('\n')}\n\nNote: Effectiveness below 25% means very poor ECO performance.`
    }

    if (lines.length > 0) return `Economizer related readings for ${time}:\n${lines.join('\n')}`
    return 'Economizer data is not available in the current report.'
  }

  // Flue gas
  if (q.includes('flue gas') || q.includes('flue')) {
    const results = searchReadings('flue gas')
    if (results.length > 0) {
      const lines = results.map((r) => {
        const v = getVal(r.tag) || '—'
        return `  • ${r.tag}: ${r.description} = ${v} ${r.unit || ''}`
      })
      return `Flue gas related readings for ${time}:\n${lines.join('\n')}`
    }
    return 'Flue gas data is not available in the current report.'
  }

  // Oxygen
  if (q.includes('oxygen') || q.includes('o2')) {
    const v = getVal('HNA10CQ901')
    if (v) return `The Oxygen (O2) level is ${v} % for the ${time} reading. This indicates the excess oxygen in the flue gas, which affects combustion efficiency.`
    return 'Oxygen data is not available in the current report.'
  }

  // Vacuum
  if (q.includes('vacuum') || q.includes('condenser') || q.includes('exhaust')) {
    const v = getVal('PI522A')
    if (v) return `The Turbine Vacuum (Exhaust Steam Pressure) is ${v} kg/cm² for the ${time} reading. A more negative value indicates better vacuum and condenser performance.`
    return 'Turbine vacuum data is not available in the current report.'
  }

  // SSC
  if (q.includes('ssc') || q.includes('specific steam consumption') || q.includes('steam consumption')) {
    const msFlow = getVal('LBA10FF001_TON')
    const tgLoad = getVal('MW001')
    if (msFlow && tgLoad && parseFloat(tgLoad) !== 0) {
      const ssc = parseFloat(msFlow) / parseFloat(tgLoad)
      return `The Turbine Specific Steam Consumption (SSC) is ${ssc.toFixed(2)} TNE/H per MW for the ${time} reading. This is calculated as Main Steam Flow (${msFlow} TNE/H) divided by TG Load (${tgLoad} MW).`
    }
    return 'Unable to calculate SSC — missing Main Steam Flow or TG Load data.'
  }

  // Drum
  if (q.includes('drum') || q.includes('boiler drum')) {
    const results = searchReadings('drum')
    if (results.length > 0) {
      const lines = results.map((r) => {
        const v = getVal(r.tag) || '—'
        return `  • ${r.tag}: ${r.description} = ${v} ${r.unit || ''}`
      })
      return `Boiler Drum readings for ${time}:\n${lines.join('\n')}`
    }
    return 'Boiler drum data is not available in the current report.'
  }

  // Superheater
  if (q.includes('superheater') || q.includes('sh3') || q.includes('sh4') || q.includes('sh1') || q.includes('sh2')) {
    const results = readings.filter((r) =>
      r.description.toLowerCase().includes('sh') || r.tag.toLowerCase().includes('hah') || r.tag.toLowerCase().includes('hbk1')
    )
    if (results.length > 0) {
      const lines = results.slice(0, 15).map((r) => {
        const v = getVal(r.tag) || '—'
        return `  • ${r.tag}: ${r.description} = ${v} ${r.unit || ''}`
      })
      return `Superheater related readings for ${time}:\n${lines.join('\n')}`
    }
    return 'Superheater data is not available in the current report.'
  }

  // Combustion air / APH
  if (q.includes('combustion air') || q.includes('aph') || q.includes('air pressure') || q.includes('air temp')) {
    const results = searchReadings('combustion air')
    if (results.length > 0) {
      const lines = results.map((r) => {
        const v = getVal(r.tag) || '—'
        return `  • ${r.tag}: ${r.description} = ${v} ${r.unit || ''}`
      })
      return `Combustion air readings for ${time}:\n${lines.join('\n')}`
    }
    return 'Combustion air data is not available in the current report.'
  }

  // Wheel chamber
  if (q.includes('wheel chamber') || q.includes('wheel')) {
    const v = getVal('PI109')
    if (v) return `The Wheel Chamber Pressure is ${v} kg/cm² for the ${time} reading. This indicates the HP turbine internal pressure.`
    return 'Wheel chamber pressure data is not available in the current report.'
  }

  // Summary / overview
  if (q.includes('summary') || q.includes('overview') || q.includes('status') || q.includes('how is') || q.includes('plant status') || q.includes('report')) {
    const summary = report.summary || {}
    const entries = Object.entries(summary)
    if (entries.length > 0) {
      const lines = entries.map(([k, v]) => `  • ${k}: ${v}`)
      return `Plant overview for ${report.report_date || 'this report'} (${time}):\n${lines.join('\n')}\n\nTotal tags in report: ${report.tag_count}`
    }
    return `This report contains ${report.tag_count} tags from sheet "${report.sheet_name}" dated ${report.report_date || 'no date'}. Ask me about specific parameters like TG load, steam pressure, economizer effectiveness, etc.`
  }

  // Search by tag
  const tagMatch = q.match(/[a-z]{2,}\d|[a-z]+\d+/i)
  if (tagMatch) {
    const results = searchReadings(tagMatch[0])
    if (results.length > 0 && results.length <= 10) {
      const lines = results.map((r) => {
        const v = getVal(r.tag) || '—'
        return `  • ${r.tag}: ${r.description} = ${v} ${r.unit || ''}`
      })
      return `Found ${results.length} matching tag(s) for "${tagMatch[0]}" (${time}):\n${lines.join('\n')}`
    }
  }

  // List all tags
  if (q.includes('list') || q.includes('all tags') || q.includes('how many') || q.includes('count')) {
    return `This report contains ${report.tag_count} tags from sheet "${report.sheet_name}" dated ${report.report_date || 'no date'}. You can ask me about specific parameters like TG load, steam flow, economizer, flue gas, oxygen, vacuum, or any tag name.`
  }

  // Greeting
  if (q.includes('hello') || q.includes('hi') || q.includes('hey') || q.includes('greet')) {
    return `Hello! I'm your Jalkheri DCS assistant. I can answer questions about the currently loaded report dated ${report.report_date || 'no date'}. You can ask me about TG load, steam pressure, temperature, economizer effectiveness, flue gas, oxygen levels, vacuum, and any tag in the report. What would you like to know?`
  }

  // Help
  if (q.includes('help') || q.includes('what can you') || q.includes('what do you')) {
    return `I can help you understand your plant data. Try asking me:\n\n  • "What is the TG load?"\n  • "What is the steam pressure and temperature?"\n  • "How is the economizer effectiveness?"\n  • "What is the oxygen level?"\n  • "What is the turbine vacuum?"\n  • "What is the SSC?"\n  • "Show me feed water readings"\n  • "What is the wheel chamber pressure?"\n  • "Give me a plant overview"\n\nI'm analyzing data from the report dated ${report.report_date || 'no date'} (${time}).`
  }

  // Fallback: try to find relevant readings
  const words = q.split(/\s+/).filter((w) => w.length > 3)
  for (const word of words) {
    const results = searchReadings(word)
    if (results.length > 0 && results.length <= 8) {
      const lines = results.map((r) => {
        const v = getVal(r.tag) || '—'
        return `  • ${r.tag}: ${r.description} = ${v} ${r.unit || ''}`
      })
      return `I found ${results.length} reading(s) related to "${word}" for ${time}:\n${lines.join('\n')}\n\nIf this isn't what you were looking for, try asking more specifically.`
    }
  }

  return `I'm not sure I understand your question. I can answer questions about the plant data from the report dated ${report.report_date || 'no date'}. Try asking about TG load, steam pressure, economizer effectiveness, oxygen levels, vacuum, or any specific tag. Type "help" for more suggestions.`
}

export default function AiAgent({ report, readings, selectedTime }: Props) {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: 'assistant',
      content: report
        ? `Hello! I'm your Jalkheri DCS assistant. I can see you have a report loaded dated ${report.report_date || 'no date'} with ${report.tag_count} tags. Ask me anything about your plant data!`
        : "Hello! I'm your Jalkheri DCS assistant. Please upload and load a report first, then I'll be able to answer questions about your plant data.",
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    },
  ])
  const [input, setInput] = useState('')
  const [thinking, setThinking] = useState(false)
  const scrollRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [messages, thinking])

  const send = useCallback(() => {
    const text = input.trim()
    if (!text || thinking) return

    const userMsg: Message = {
      role: 'user',
      content: text,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    }
    setMessages((prev) => [...prev, userMsg])
    setInput('')
    setThinking(true)

    // Simulate thinking delay for natural feel
    setTimeout(() => {
      const reply = generateReply(text, report, readings, selectedTime)
      const assistantMsg: Message = {
        role: 'assistant',
        content: reply,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      }
      setMessages((prev) => [...prev, assistantMsg])
      setThinking(false)
    }, 400 + Math.random() * 600)
  }, [input, thinking, report, readings, selectedTime])

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      send()
    }
  }

  const suggestions = [
    'What is the TG load?',
    'How is the economizer effectiveness?',
    'What is the steam pressure and temperature?',
    'What is the oxygen level?',
    'Give me a plant overview',
  ]

  return (
    <div className="ai-agent-page">
      <div className="ai-chat-container">
        <div className="ai-chat-header">
          <div className="ai-chat-header-icon">
            <Sparkles size={20} />
          </div>
          <div>
            <div className="ai-chat-title">DCS Assistant</div>
            <div className="ai-chat-subtitle">
              {report
                ? `Analyzing report: ${report.report_date || 'no date'} · ${report.tag_count} tags`
                : 'No report loaded'}
            </div>
          </div>
        </div>

        <div className="ai-chat-messages" ref={scrollRef}>
          {messages.map((msg, i) => (
            <div key={i} className={`ai-message ai-message-${msg.role}`}>
              <div className="ai-message-avatar">
                {msg.role === 'assistant' ? <Bot size={18} /> : <User size={18} />}
              </div>
              <div className="ai-message-bubble">
                <div className="ai-message-text">{msg.content}</div>
                <div className="ai-message-time">{msg.time}</div>
              </div>
            </div>
          ))}
          {thinking && (
            <div className="ai-message ai-message-assistant">
              <div className="ai-message-avatar">
                <Bot size={18} />
              </div>
              <div className="ai-message-bubble">
                <div className="ai-thinking">
                  <span></span>
                  <span></span>
                  <span></span>
                </div>
              </div>
            </div>
          )}
        </div>

        {messages.length <= 1 && !thinking && (
          <div className="ai-suggestions">
            {suggestions.map((s) => (
              <button
                key={s}
                className="ai-suggestion-chip"
                onClick={() => {
                  setInput(s)
                  inputRef.current?.focus()
                }}
              >
                {s}
              </button>
            ))}
          </div>
        )}

        <div className="ai-chat-input-area">
          <textarea
            ref={inputRef}
            className="ai-chat-input"
            placeholder="Ask about TG load, steam pressure, economizer, oxygen..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            rows={1}
            disabled={thinking}
          />
          <button
            className="ai-send-btn"
            onClick={send}
            disabled={!input.trim() || thinking}
          >
            {thinking ? <Loader2 size={18} className="spin" /> : <Send size={18} />}
          </button>
        </div>
      </div>
    </div>
  )
}
